#!/usr/bin/env python3
import tensorflow as tf

cluster = tf.train.ClusterSpec({'master': [], 'worker': [], 'slave': []})
server = tf.train.Server(cluster, job_name='worker', task_index=0)
print(server.server_def)
server.join()
